cmake_minimum_required(VERSION 2.8.12...3.5)
project(w2c2_embedding C CXX)

enable_testing()
if(NOT TARGET w2c2::w2c2_lib)
    find_package(w2c2 CONFIG REQUIRED)
endif()
find_package(Threads)

foreach(STANDARD 90 99)
    add_executable(w2c2_embedding_c${STANDARD} main.c)
    set_target_properties(w2c2_embedding_c${STANDARD} PROPERTIES C_STANDARD ${STANDARD})
    if(STANDARD EQUAL 99)
        target_compile_definitions(w2c2_embedding_c${STANDARD} PRIVATE TEST_STDBOOL=1)
    endif()
    target_link_libraries(w2c2_embedding_c${STANDARD} w2c2::w2c2_lib)
    if(CMAKE_USE_PTHREADS_INIT)
        target_compile_definitions(w2c2_embedding_c${STANDARD} PRIVATE HAS_PTHREAD=1)
        if(TARGET Threads::Threads)
            target_link_libraries(w2c2_embedding_c${STANDARD} Threads::Threads)
        else()
            target_link_libraries(w2c2_embedding_c${STANDARD} ${CMAKE_THREAD_LIBS_INIT})
        endif()
    endif()
    add_test(NAME embedding_c${STANDARD} COMMAND w2c2_embedding_c${STANDARD})
endforeach()

add_executable(w2c2_embedding_cpp main.cpp)
target_link_libraries(w2c2_embedding_cpp w2c2::w2c2_lib)
add_test(NAME embedding_cpp COMMAND w2c2_embedding_cpp)
