cmake_minimum_required(VERSION 2.8.12...3.5)
project(w2c2_embedding C CXX)

enable_testing()
if(NOT TARGET w2c2::w2c2_lib)
    find_package(w2c2 CONFIG REQUIRED)
endif()

find_package(Threads)

foreach(STANDARD 90 99)
    add_executable(w2c2_embedding_c${STANDARD} main.c)
    set_target_properties(w2c2_embedding_c${STANDARD} PROPERTIES C_STANDARD ${STANDARD})
    if(STANDARD EQUAL 99)
        target_compile_definitions(w2c2_embedding_c${STANDARD} PRIVATE TEST_STDBOOL=1)
    endif()
    target_link_libraries(w2c2_embedding_c${STANDARD} w2c2::w2c2_lib)
    if(CMAKE_USE_PTHREADS_INIT)
        target_compile_definitions(w2c2_embedding_c${STANDARD} PRIVATE HAS_PTHREAD=1)
        if(TARGET Threads::Threads)
            target_link_libraries(w2c2_embedding_c${STANDARD} Threads::Threads)
        else()
            target_link_libraries(w2c2_embedding_c${STANDARD} ${CMAKE_THREAD_LIBS_INIT})
        endif()
    endif()
    add_test(NAME embedding_c${STANDARD} COMMAND w2c2_embedding_c${STANDARD})
endforeach()

add_executable(w2c2_embedding_cpp main.cpp)
set_target_properties(w2c2_embedding_cpp PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED YES)
target_link_libraries(w2c2_embedding_cpp w2c2::w2c2_lib)
add_test(NAME embedding_cpp COMMAND w2c2_embedding_cpp)

if(TARGET w2c2 AND NOT CMAKE_CROSSCOMPILING)
    foreach(NAME binary_names c_strings)
        set(GENERATED "${CMAKE_CURRENT_BINARY_DIR}/test_${NAME}")
        add_custom_command(OUTPUT "${GENERATED}.c" "${GENERATED}.h"
            COMMAND w2c2 "${CMAKE_CURRENT_SOURCE_DIR}/../gen/${NAME}.wasm" "${GENERATED}.c"
            DEPENDS w2c2 "${CMAKE_CURRENT_SOURCE_DIR}/../gen/${NAME}.wasm")
        add_custom_target(w2c2_generate_${NAME} DEPENDS "${GENERATED}.c" "${GENERATED}.h")
        configure_file("../${NAME}_test.c" "${NAME}_main.c" COPYONLY)
        foreach(LANGUAGE c cpp)
            set(SOURCE "${CMAKE_CURRENT_BINARY_DIR}/${NAME}.${LANGUAGE}")
            file(WRITE "${SOURCE}" "#include \"${NAME}_main.c\"\n#include \"test_${NAME}.c\"\n")
            set(TARGET w2c2_${NAME}_${LANGUAGE})
            add_executable(${TARGET} "${SOURCE}")
            add_dependencies(${TARGET} w2c2_generate_${NAME})
            set_target_properties(${TARGET} PROPERTIES
                C_STANDARD 90 CXX_STANDARD 11 CXX_STANDARD_REQUIRED YES)
            target_link_libraries(${TARGET} w2c2::w2c2_lib)
            if(MSVC)
                if(LANGUAGE STREQUAL "cpp")
                    target_compile_options(${TARGET} PRIVATE /Zc:strictStrings)
                endif()
            else()
                target_compile_options(${TARGET} PRIVATE -Werror=write-strings)
            endif()
            add_test(NAME ${NAME}_${LANGUAGE} COMMAND ${TARGET})
        endforeach()
    endforeach()
    if(APPLE
        AND NOT CMAKE_SYSTEM_VERSION VERSION_LESS 9
        AND (NOT CMAKE_OSX_DEPLOYMENT_TARGET OR NOT CMAKE_OSX_DEPLOYMENT_TARGET VERSION_LESS 10.5))
        configure_file("../gen/memory_init.1.wasm" "data.wasm" COPYONLY)
        set(SECTCREATE_SOURCE "${CMAKE_CURRENT_BINARY_DIR}/sectcreate.c")
        set(SECTCREATE_DATA "${CMAKE_CURRENT_BINARY_DIR}/m4_data.data")
        add_custom_command(OUTPUT "${SECTCREATE_SOURCE}" "${CMAKE_CURRENT_BINARY_DIR}/sectcreate.h" "${SECTCREATE_DATA}"
            COMMAND w2c2 -d sectcreate2 "${CMAKE_CURRENT_BINARY_DIR}/data.wasm" "${SECTCREATE_SOURCE}"
            DEPENDS w2c2 "${CMAKE_CURRENT_BINARY_DIR}/data.wasm"
            VERBATIM)
        add_executable(w2c2_sectcreate sectcreate_test.c "${SECTCREATE_SOURCE}")
        target_include_directories(w2c2_sectcreate PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
        target_link_libraries(w2c2_sectcreate w2c2::w2c2_lib)
        set_target_properties(w2c2_sectcreate PROPERTIES C_STANDARD 90
            LINK_FLAGS "-Wl,-pie -Wl,-sectcreate,__DATA,m4_data,\"${SECTCREATE_DATA}\"")
        add_test(NAME sectcreate COMMAND w2c2_sectcreate)
    endif()
endif()
