(module
  (import "env" "memory" (memory 1 2))
  (data $active (i32.const 0) "ABC")
  (data $passive "abcd")
  (func (export "load") (param i32) (result i32)
    (i32.load offset=1 (local.get 0)))
  (func (export "store") (param i32 i32)
    (i32.store offset=1 (local.get 0) (local.get 1)))
  (func (export "atomic_load") (param i32) (result i32)
    (i32.atomic.load offset=8 (local.get 0)))
  (func (export "atomic_store") (param i32 i32)
    (i32.atomic.store offset=8 (local.get 0) (local.get 1)))
  (func (export "add") (param i32) (result i32)
    (i32.atomic.rmw.add offset=8 (local.get 0) (i32.const 1)))
  (func (export "cmpxchg") (param i32) (result i32)
    (i32.atomic.rmw.cmpxchg offset=8 (local.get 0) (i32.const 0) (i32.const 1)))
  (func (export "init") (param i32 i32 i32)
    (memory.init $passive (local.get 0) (local.get 1) (local.get 2)))
  (func (export "active") (param i32 i32 i32)
    (memory.init $active (local.get 0) (local.get 1) (local.get 2)))
  (func (export "drop") (data.drop $passive))
  (func (export "copy") (param i32 i32 i32)
    (memory.copy (local.get 0) (local.get 1) (local.get 2)))
  (func (export "fill") (param i32 i32 i32)
    (memory.fill (local.get 0) (local.get 1) (local.get 2))))
