</$objtype/mkfile

OFILES = array.$O \
	c.$O \
	compat.$O \
	debug.$O \
	export.$O \
	file.$O \
	instruction.$O \
	main.$O \
	opcode.$O \
	reader.$O \
	section.$O \
	stringbuilder.$O \
	valuetype.$O

CFLAGS = -D_POSIX_SOURCE -D_BSD_EXTENSION -DPLAN9 -DHAS_UNISTD -DHAS_SYSTIME -DHAS_STRDUP 

default:V: w2c2

%.$O: %.c
	pcc $CFLAGS -c $stem.c -o $target

w2c2:V: $OFILES
	$LD -o w2c2 $OFILES

clean:V:
	rm -f *.$O
	rm -f w2c2
