#include <stdio.h>
#include "opcode_test.h"
#include "opcode.h"

void
testOpcodes(void) {
    WasmOpcode opcode = 0;
    for (; opcode < 0xFF; opcode++) {
        const char* description = wasmOpcodeDescription(opcode);
        if (strcmp(description, "unknown") == 0) {
            continue;
        }
        switch (opcode) {
        case wasmOpcodeUnreachable:
        case wasmOpcodeNop:
        case wasmOpcodeBlock:
        case wasmOpcodeLoop:
        case wasmOpcodeIf:
        case wasmOpcodeElse:
        case wasmOpcodeEnd:
        case wasmOpcodeBr:
        case wasmOpcodeBrIf:
        case wasmOpcodeBrTable:
        case wasmOpcodeReturn:
        case wasmOpcodeCall:
        case wasmOpcodeCallIndirect:
        case wasmOpcodeDrop:
        case wasmOpcodeSelect:
        case wasmOpcodeLocalGet:
        case wasmOpcodeLocalSet:
        case wasmOpcodeLocalTee:
        case wasmOpcodeGlobalGet:
        case wasmOpcodeGlobalSet:
        case wasmOpcodeI32Store:
        case wasmOpcodeI32Store8:
        case wasmOpcodeI32Store16:
        case wasmOpcodeI64Store:
        case wasmOpcodeI64Store8:
        case wasmOpcodeI64Store16:
        case wasmOpcodeI64Store32:
        case wasmOpcodeF32Store:
        case wasmOpcodeF64Store:
        case wasmOpcodeThreadsPrefix:
        case wasmOpcodeMiscPrefix:
            continue;

        case wasmOpcodeI32Load:
        case wasmOpcodeI64Load:
        case wasmOpcodeF32Load:
        case wasmOpcodeF64Load:
        case wasmOpcodeI32Load8S:
        case wasmOpcodeI32Load8U:
        case wasmOpcodeI32Load16S:
        case wasmOpcodeI32Load16U:
        case wasmOpcodeI64Load8S:
        case wasmOpcodeI64Load8U:
        case wasmOpcodeI64Load16S:
        case wasmOpcodeI64Load16U:
        case wasmOpcodeI64Load32S:
        case wasmOpcodeI64Load32U:
        case wasmOpcodeMemorySize:
        case wasmOpcodeMemoryGrow:
        case wasmOpcodeI32Const:
        case wasmOpcodeI64Const:
        case wasmOpcodeF32Const:
        case wasmOpcodeF64Const:
        case wasmOpcodeI32Eqz:
        case wasmOpcodeI32Eq:
        case wasmOpcodeI32Ne:
        case wasmOpcodeI32LtS:
        case wasmOpcodeI32LtU:
        case wasmOpcodeI32GtS:
        case wasmOpcodeI32GtU:
        case wasmOpcodeI32LeS:
        case wasmOpcodeI32LeU:
        case wasmOpcodeI32GeS:
        case wasmOpcodeI32GeU:
        case wasmOpcodeI64Eqz:
        case wasmOpcodeI64Eq:
        case wasmOpcodeI64Ne:
        case wasmOpcodeI64LtS:
        case wasmOpcodeI64LtU:
        case wasmOpcodeI64GtS:
        case wasmOpcodeI64GtU:
        case wasmOpcodeI64LeS:
        case wasmOpcodeI64LeU:
        case wasmOpcodeI64GeS:
        case wasmOpcodeI64GeU:
        case wasmOpcodeF32Eq:
        case wasmOpcodeF32Ne:
        case wasmOpcodeF32Lt:
        case wasmOpcodeF32Gt:
        case wasmOpcodeF32Le:
        case wasmOpcodeF32Ge:
        case wasmOpcodeF64Eq:
        case wasmOpcodeF64Ne:
        case wasmOpcodeF64Lt:
        case wasmOpcodeF64Gt:
        case wasmOpcodeF64Le:
        case wasmOpcodeF64Ge:
        case wasmOpcodeI32Clz:
        case wasmOpcodeI32Ctz:
        case wasmOpcodeI32PopCnt:
        case wasmOpcodeI32Add:
        case wasmOpcodeI32Sub:
        case wasmOpcodeI32Mul:
        case wasmOpcodeI32DivS:
        case wasmOpcodeI32DivU:
        case wasmOpcodeI32RemS:
        case wasmOpcodeI32RemU:
        case wasmOpcodeI32And:
        case wasmOpcodeI32Or:
        case wasmOpcodeI32Xor:
        case wasmOpcodeI32Shl:
        case wasmOpcodeI32ShrS:
        case wasmOpcodeI32ShrU:
        case wasmOpcodeI32Rotl:
        case wasmOpcodeI32Rotr:
        case wasmOpcodeI64Clz:
        case wasmOpcodeI64Ctz:
        case wasmOpcodeI64PopCnt:
        case wasmOpcodeI64Add:
        case wasmOpcodeI64Sub:
        case wasmOpcodeI64Mul:
        case wasmOpcodeI64DivS:
        case wasmOpcodeI64DivU:
        case wasmOpcodeI64RemS:
        case wasmOpcodeI64RemU:
        case wasmOpcodeI64And:
        case wasmOpcodeI64Or:
        case wasmOpcodeI64Xor:
        case wasmOpcodeI64Shl:
        case wasmOpcodeI64ShrS:
        case wasmOpcodeI64ShrU:
        case wasmOpcodeI64Rotl:
        case wasmOpcodeI64Rotr:
        case wasmOpcodeF32Abs:
        case wasmOpcodeF32Neg:
        case wasmOpcodeF32Ceil:
        case wasmOpcodeF32Floor:
        case wasmOpcodeF32Trunc:
        case wasmOpcodeF32Nearest:
        case wasmOpcodeF32Sqrt:
        case wasmOpcodeF32Add:
        case wasmOpcodeF32Sub:
        case wasmOpcodeF32Mul:
        case wasmOpcodeF32Div:
        case wasmOpcodeF32Min:
        case wasmOpcodeF32Max:
        case wasmOpcodeF32CopySign:
        case wasmOpcodeF64Abs:
        case wasmOpcodeF64Neg:
        case wasmOpcodeF64Ceil:
        case wasmOpcodeF64Floor:
        case wasmOpcodeF64Trunc:
        case wasmOpcodeF64Nearest:
        case wasmOpcodeF64Sqrt:
        case wasmOpcodeF64Add:
        case wasmOpcodeF64Sub:
        case wasmOpcodeF64Mul:
        case wasmOpcodeF64Div:
        case wasmOpcodeF64Min:
        case wasmOpcodeF64Max:
        case wasmOpcodeF64CopySign:
        case wasmOpcodeI32WrapI64:
        case wasmOpcodeI32TruncF32S:
        case wasmOpcodeI32TruncF32U:
        case wasmOpcodeI32TruncF64S:
        case wasmOpcodeI32TruncF64U:
        case wasmOpcodeI64ExtendI32S:
        case wasmOpcodeI64ExtendI32U:
        case wasmOpcodeI64TruncF32S:
        case wasmOpcodeI64TruncF32U:
        case wasmOpcodeI64TruncF64S:
        case wasmOpcodeI64TruncF64U:
        case wasmOpcodeF32ConvertI32S:
        case wasmOpcodeF32ConvertI32U:
        case wasmOpcodeF32ConvertI64S:
        case wasmOpcodeF32ConvertI64U:
        case wasmOpcodeF32DemoteF64:
        case wasmOpcodeF64ConvertI32S:
        case wasmOpcodeF64ConvertI32U:
        case wasmOpcodeF64ConvertI64S:
        case wasmOpcodeF64ConvertI64U:
        case wasmOpcodeF64PromoteF32:
        case wasmOpcodeI32ReinterpretF32:
        case wasmOpcodeI64ReinterpretF64:
        case wasmOpcodeF32ReinterpretI32:
        case wasmOpcodeF64ReinterpretI64:
        case wasmOpcodeI32Extend8S:
        case wasmOpcodeI32Extend16S:
        case wasmOpcodeI64Extend8S:
        case wasmOpcodeI64Extend16S:
        case wasmOpcodeI64Extend32S:
            break;
        }
        wasmOpcodeResultType(opcode);
    }

    fprintf(stderr, "PASS testOpcodes\n");
}
